USE [TEST_DB]
GO

/****** Object:  Table [dbo].[Book]    Script Date: 2018/4/3 上午 11:54:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Book](
	[Pk_Book_Id] [int] NOT NULL,
	[Name] [varchar](255) NULL,
	[ISBN] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Pk_Book_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

